// Generated by CoffeeScript 1.4.0
(function() {
  var AgreeablenessFactor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AgreeablenessFactor = (function(_super) {

    __extends(AgreeablenessFactor, _super);

    function AgreeablenessFactor() {
      AgreeablenessFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_AGREEABLENESS);
    }

    return AgreeablenessFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.AgreeablenessFactor = AgreeablenessFactor;

}).call(this);
