// Generated by CoffeeScript 1.10.0
(function() {
  var AgreeablenessFactor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  AgreeablenessFactor = (function(superClass) {
    extend(AgreeablenessFactor, superClass);

    function AgreeablenessFactor() {
      AgreeablenessFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_AGREEABLENESS);
    }

    return AgreeablenessFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.AgreeablenessFactor = AgreeablenessFactor;

}).call(this);
