// Generated by CoffeeScript 1.10.0
(function() {
  var getRandomElements, pushMany;

  pushMany = function(arr, objects) {
    var j, len, obj, results;
    results = [];
    for (j = 0, len = objects.length; j < len; j++) {
      obj = objects[j];
      results.push(arr.push(obj));
    }
    return results;
  };

  window.pushMany = pushMany;

  getRandomElements = function(arr, numElements) {
    var copy, elements, i, obj;
    copy = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = arr.length; j < len; j++) {
        obj = arr[j];
        results.push(obj);
      }
      return results;
    })();
    return elements = (function() {
      var j, ref, results;
      results = [];
      for (i = j = 1, ref = numElements; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        results.push(copy.splice(Math.floor(Math.random() * copy.length), 1)[0]);
      }
      return results;
    })();
  };

  window.getRandomElements = getRandomElements;

  Array.prototype.shuffle = function() {
    var counter, index, temp;
    counter = this.length;
    temp;
    index;
    while (counter > 0) {
      index = Math.floor(Math.random() * counter);
      counter--;
      temp = this[counter];
      this[counter] = this[index];
      this[index] = temp;
    }
    return this;
  };

}).call(this);
