// Generated by CoffeeScript 1.10.0

/*
	ASDR value wrapper
 */

(function() {
  var ASDR;

  ASDR = (function() {
    function ASDR(attack, decay, sustain, release) {
      this.attack = attack;
      this.decay = decay;
      this.sustain = sustain;
      this.release = release;
    }

    ASDR.prototype.set = function(attack, decay, sustain, release) {
      this.attack = attack;
      this.decay = decay;
      this.sustain = sustain;
      this.release = release;
    };

    ASDR.prototype.getTimeUntilRelease = function() {
      return this.attack + this.decay;
    };

    ASDR.prototype.getEnvelopeDuration = function() {
      return this.attack + this.decay + this.release;
    };

    return ASDR;

  })();

  window.Audanism.Audio.Module.ASDR = ASDR;

}).call(this);
