// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  window.Audanism = {
    'Audio': {
      'FX': {},
      'Instrument': {},
      'Module': {},
      'Synthesizer': {}
    },
    'Calculator': {},
    'Environment': {},
    'Event': {},
    'Factor': {},
    'Graphic': {},
    'GUI': {},
    'Node': {},
    'SourceAdapter': {},
    'Util': {}
  };

  $(window).ready(function() {
    return window.Audanism.appInstance = new Audanism.Environment.Environment;
  });

}).call(this);
