// Generated by CoffeeScript 1.10.0

/*
	The Audanism object hierarchy.
 */

(function() {
  window.Audanism = {
    'Audio': {
      'FX': {},
      'Instrument': {},
      'Module': {},
      'Synthesizer': {}
    },
    'Calculator': {},
    'Environment': {},
    'Event': {},
    'Factor': {},
    'Graphic': {},
    'GUI': {},
    'Node': {},
    'SourceAdapter': {},
    'Util': {}
  };

  $(window).ready((function(_this) {
    return function() {
      return window.Audanism.appInstance = new Audanism.Environment.Environment;
    };
  })(this));

}).call(this);
