// Generated by CoffeeScript 1.4.0

/*
	Class that takes care of all the music
*/


(function() {
  var Conductor;

  Conductor = (function() {

    function Conductor() {
      this.organism = null;
      this.audiolet = new Audiolet();
      this.noise = new Audanism.Sound.Noise(this.audiolet);
      this.nodeSounds = [];
    }

    Conductor.prototype.setOrganism = function(organism) {
      return this.organism = organism;
    };

    Conductor.prototype.mute = function() {
      return this.noise.gain.gain.setValue(0);
    };

    Conductor.prototype.unmute = function() {
      return this.noise.gain.gain.setValue(1);
    };

    Conductor.prototype.updateSounds = function() {
      var disharmonyData, disharmonyNew, disharmonyOld, disharmonyRatio;
      disharmonyData = this.organism.getDisharmonyHistoryData(200);
      disharmonyNew = disharmonyData[disharmonyData.length - 1][2];
      disharmonyOld = disharmonyData[0][2];
      disharmonyRatio = disharmonyNew / disharmonyOld;
      return this.noise.lpf.frequency.setValue(disharmonyRatio * 1000);
    };

    return Conductor;

  })();

  Audanism.Sound.Conductor = Conductor;

}).call(this);
