// Generated by CoffeeScript 1.4.0
(function() {
  var ConscientiousnessFactor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ConscientiousnessFactor = (function(_super) {

    __extends(ConscientiousnessFactor, _super);

    function ConscientiousnessFactor() {
      ConscientiousnessFactor.__super__.constructor.call(this, Factor.TYPE_CONSCIENTIOUSNESS, 70);
    }

    return ConscientiousnessFactor;

  })(Factor);

  window.ConscientiousnessFactor = ConscientiousnessFactor;

}).call(this);
