// Generated by CoffeeScript 1.10.0
(function() {
  var ConscientiousnessFactor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ConscientiousnessFactor = (function(superClass) {
    extend(ConscientiousnessFactor, superClass);

    function ConscientiousnessFactor() {
      ConscientiousnessFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_CONSCIENTIOUSNESS);
    }

    return ConscientiousnessFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.ConscientiousnessFactor = ConscientiousnessFactor;

}).call(this);
