// Generated by CoffeeScript 1.4.0

/*
	Environment
*/


(function() {
  var Environment,
    _this = this;

  Environment = (function() {

    Environment.NUM_ORGANISMS = 1;

    Environment.TIME_INTERVAL = 50;

    function Environment() {
      var i, organism, _i, _len, _ref;
      this._iterationCount = 0;
      this._isRunning = false;
      this._isSingleStep = true;
      this._organisms = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 1, _ref = Environment.NUM_ORGANISMS; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
          _results.push(new Organism);
        }
        return _results;
      })();
      this._gui = new GUI;
      _ref = this._organisms;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        organism = _ref[_i];
        this._gui.update(organism.getFactors(), organism.getNodes(), organism.getDisharmonyHistoryData(-1));
      }
      this.listenToControls();
      this.createInfluenceSources();
      this.run();
    }

    Environment.prototype.run = function() {
      var _this = this;
      this._intervalId = setInterval(function() {
        return _this.handleIteration();
      }, Environment.TIME_INTERVAL);
      return this.handleIteration();
    };

    Environment.prototype.start = function() {
      return this._isRunning = true;
    };

    Environment.prototype.pause = function() {
      return this._isRunning = false;
    };

    Environment.prototype.stop = function() {
      this._isRunning = false;
      return clearInterval(this._intervalId);
    };

    Environment.prototype.step = function() {
      return this._isSingleStep = true;
    };

    Environment.prototype.listenToControls = function() {
      var _this = this;
      $(document).on('dmstart', function(e) {
        return _this.start();
      });
      $(document).on('dmpause', function(e) {
        return _this.pause();
      });
      $(document).on('dmstop', function(e) {
        return _this.stop();
      });
      return $(document).on('dmstep', function(e) {
        return _this.step();
      });
    };

    Environment.prototype.handleIteration = function() {
      var organism, _i, _len, _ref, _results;
      this._iterationCount++;
      if (this._isRunning || this._isSingleStep) {
        _ref = this._organisms;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          organism = _ref[_i];
          organism.performNodeComparison();
          this._gui.update(organism.getFactors(), organism.getNodes(), organism.getDisharmonyHistoryData(-1));
          _results.push(this._isSingleStep = false);
        }
        return _results;
      }
    };

    Environment.prototype.createInfluenceSources = function() {
      var sourceAdapter, _i, _len, _ref, _results;
      this._influenceSources = [];
      this._influenceSources.push(new RandomSourceAdapter(this));
      _ref = this._influenceSources;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sourceAdapter = _ref[_i];
        _results.push(sourceAdapter.activate());
      }
      return _results;
    };

    Environment.prototype.influence = function(influenceData) {
      var argNum, argVal, cell, factor, factors, node, nodes, num, numType, organism, type, valType, valueMod, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1;
      if (!this._isRunning) {
        return;
      }
      console.log("---");
      console.log("#influence", influenceData);
      if (influenceData.random != null) {
        type = influenceData.random['object'];
        argNum = influenceData.random.num;
        argVal = influenceData.random.valueModifier;
        num = 0;
        valueMod = -1;
        numType = typeof argNum;
        if (numType === 'integer') {
          num = argNum;
        } else if (numType === 'array') {
          num = Math.randomRange(argNum[1], argNum[0]);
        } else if (numType === 'string' && argNum === 'rand') {
          num = Math.randomRange(type === 'factor' ? 1 : 5);
        }
        if (type === 'factor') {
          _ref = this._organisms;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            organism = _ref[_i];
            factors = getRandomElements(organism.getFactors(), num);
            for (_j = 0, _len1 = factors.length; _j < _len1; _j++) {
              factor = factors[_j];
              valType = typeof argVal;
              if (valType === 'integer') {
                valueMod = argVal;
              } else if (valType === 'array') {
                valueMod = Math.randomRange(argVal[1], argVal[0]);
              } else if (valType === 'string' && argVal === 'rand') {
                console.log("        getting values using 'rand'");
                valueMod = Math.randomRange(5, -5);
              }
              console.log("    --> influence: factor " + factor.factorType + " by " + valueMod);
              console.log("        ... before: " + factor);
              organism.getFactorOfType(factor.factorType).addValue(valueMod);
              console.log("        ... after: " + factor);
            }
          }
        } else if (type === 'node') {
          _ref1 = this._organisms;
          for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
            organism = _ref1[_k];
            nodes = getRandomElements(organism.getNodes(), num);
            for (_l = 0, _len3 = nodes.length; _l < _len3; _l++) {
              node = nodes[_l];
              valType = typeof argVal;
              if (valType === 'integer') {
                valueMod = argVal;
              } else if (valType === 'array') {
                valueMod = Math.randomRange(argVal[1], argVal[0]);
              } else if (valType === 'string' && argVal === 'rand') {
                console.log("        getting values using 'rand'");
                valueMod = Math.randomRange(20, -20);
              }
              cell = getRandomElements(node.getCells(), 1)[0];
              console.log("    --> influence: node " + node.nodeId + "->" + cell.factorType + " by " + valueMod);
              console.log("        ... before: " + node);
              organism.getFactorOfType(factor.factorType).addValue(valueMod);
              console.log("        ... after: " + node);
            }
          }
        }
      }
      return console.log("---");
    };

    return Environment;

  })();

  window.Environment = Environment;

  $(window).ready(function() {
    var environment;
    environment = new Environment;
    return window.environment = environment;
  });

}).call(this);
