// Generated by CoffeeScript 1.10.0

/*
	EventDispatcher

	The event dispatcher is an abstraction of jQuery's event dispatchment.

	@author Alexander Wallin
	@url    http://alexanderwallin.com
 */

(function() {
  var EventDispatcher;

  EventDispatcher = (function() {
    function EventDispatcher() {}

    EventDispatcher.prototype.on = function(eventName, callback, context) {
      if (context) {
        callback.bind(context);
      }
      return $(document).on(eventName, (function(_this) {
        return function(e) {
          return callback.apply(null, arguments.slice(1));
        };
      })(this));
    };

    EventDispatcher.prototype.listen = function(eventName, listener, callback) {
      return $(document).on(eventName, (function(_this) {
        return function(e) {
          return callback.call(listener, arguments[1]);
        };
      })(this));
    };

    EventDispatcher.prototype.trigger = function(eventName, args) {
      return $(document).trigger(eventName, args);
    };

    return EventDispatcher;

  })();

  window.Audanism.Event.EventDispatcher = EventDispatcher;

  window.EventDispatcher = new EventDispatcher();

}).call(this);
