// Generated by CoffeeScript 1.4.0

/*
	Event dispatcher. Gets rid of context issues.
*/


(function() {
  var EventDispatcher;

  EventDispatcher = (function() {

    function EventDispatcher() {}

    EventDispatcher.prototype.listen = function(eventName, listener, callback) {
      var _this = this;
      return $(document).on(eventName, function(e) {
        return callback.call(listener, arguments[1]);
      });
    };

    EventDispatcher.prototype.trigger = function(eventName, args) {
      return $(document).trigger(eventName, args);
    };

    return EventDispatcher;

  })();

  window.Audanism.Event.EventDispatcher = EventDispatcher;

  window.EventDispatcher = new EventDispatcher();

}).call(this);
