// Generated by CoffeeScript 1.4.0

/*
	EventDispatcher

	The event dispatcher is an abstraction of jQuery's event dispatchment.

	@author Alexander Wallin
	@url    http://alexanderwallin.com
*/


(function() {
  var EventDispatcher;

  EventDispatcher = (function() {

    function EventDispatcher() {}

    EventDispatcher.prototype.on = function(eventName, callback, context) {
      var _this = this;
      if (context) {
        callback.bind(context);
      }
      return $(document).on(eventName, function(e) {
        return callback.apply(null, arguments.slice(1));
      });
    };

    EventDispatcher.prototype.listen = function(eventName, listener, callback) {
      var _this = this;
      return $(document).on(eventName, function(e) {
        return callback.call(listener, arguments[1]);
      });
    };

    EventDispatcher.prototype.trigger = function(eventName, args) {
      return $(document).trigger(eventName, args);
    };

    return EventDispatcher;

  })();

  window.Audanism.Event.EventDispatcher = EventDispatcher;

  window.EventDispatcher = new EventDispatcher();

}).call(this);
