// Generated by CoffeeScript 1.10.0
(function() {
  var ExtraversionFactor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ExtraversionFactor = (function(superClass) {
    extend(ExtraversionFactor, superClass);

    function ExtraversionFactor() {
      ExtraversionFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_EXTRAVERSION);
    }

    return ExtraversionFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.ExtraversionFactor = ExtraversionFactor;

}).call(this);
