// Generated by CoffeeScript 1.4.0
(function() {
  var ExtraversionFactor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ExtraversionFactor = (function(_super) {

    __extends(ExtraversionFactor, _super);

    function ExtraversionFactor() {
      ExtraversionFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_EXTRAVERSION);
    }

    return ExtraversionFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.ExtraversionFactor = ExtraversionFactor;

}).call(this);
