// Generated by CoffeeScript 1.10.0

/*
 */

(function() {
  var FactorComparer;

  FactorComparer = (function() {
    function FactorComparer() {}

    FactorComparer.getFactorDisharmonyForNodes = function(factor, nodes) {
      var disharmony, i, len, node;
      disharmony = 0;
      for (i = 0, len = nodes.length; i < len; i++) {
        node = nodes[i];
        disharmony += FactorComparer.getFactorDisharmonyForNode(factor, node);
      }
      return disharmony;
    };

    FactorComparer.getFactorDisharmonyForNode = function(factor, node) {
      return 0.01 * Math.abs(factor.factorValue - node.getCellValue(factor.factorType));
    };

    FactorComparer.getRelativeDisharmonyForFactors = function(factors) {};

    return FactorComparer;

  })();

  window.Audanism.Calculator.FactorComparer = FactorComparer;

}).call(this);
