// Generated by CoffeeScript 1.4.0

/*
*/


(function() {
  var FactorComparer;

  FactorComparer = (function() {

    function FactorComparer() {}

    FactorComparer.getFactorDisharmonyForNodes = function(factor, nodes) {
      var disharmony, node, _i, _len;
      disharmony = 0;
      for (_i = 0, _len = nodes.length; _i < _len; _i++) {
        node = nodes[_i];
        disharmony += FactorComparer.getFactorDisharmonyForNode(factor, node);
      }
      return disharmony;
    };

    FactorComparer.getFactorDisharmonyForNode = function(factor, node) {
      return 0.01 * Math.abs(factor.factorValue - node.getCellValue(factor.factorType));
    };

    FactorComparer.getRelativeDisharmonyForFactors = function(factors) {};

    return FactorComparer;

  })();

  window.Audanism.Calculator.FactorComparer = FactorComparer;

}).call(this);
