// Generated by CoffeeScript 1.10.0

/*
	FX super-class
 */

(function() {
  var FX;

  FX = (function() {
    function FX(_in, out) {
      this["in"] = _in;
      this.out = out;
    }

    return FX;

  })();

  window.Audanism.Audio.FX.FX = FX;

}).call(this);
