// Generated by CoffeeScript 1.10.0

/*
	Harmonizer - utility for getting notes, scale notes, frequeceies
	and more.
 */

(function() {
  var Harmonizer;

  Harmonizer = (function() {
    function Harmonizer() {}

    Harmonizer.SCALE_MAJOR = [0, 2, 4, 5, 7, 9, 11];

    Harmonizer.SCALE_MINOR = [0, 2, 3, 5, 7, 9, 10];

    Harmonizer.getFreqFromNote = function(note, scale) {
      var closestNoteInOctave, i, len, n, ref;
      if (scale == null) {
        scale = 'minor';
      }
      note = 440 * Math.pow(2, (note - 69) / 12);
      if (scale && scale === 'minor') {
        note = Math.round(note);
        closestNoteInOctave = Math.abs(note - 69) % 12;
        ref = window.Audanism.Audio.Module.Harmonizer.SCALE_MINOR;
        for (i = 0, len = ref.length; i < len; i++) {
          n = ref[i];
          if (note === n) {
            break;
          }
          note = note + 1;
        }
      }
      if (scale && scale === 'major') {
        console.log();
      }
      return note;
    };

    Harmonizer.getNoteFromFreq = function(freq) {
      return Math.round(logWithBase(2, freq / 440) * 12 + 69);
    };

    return Harmonizer;

  })();

  window.Audanism.Audio.Module.Harmonizer = Harmonizer;

}).call(this);
