// Generated by CoffeeScript 1.10.0

/*
	Impulse module
 */

(function() {
  var Impulse;

  Impulse = (function() {
    function Impulse(seconds, decay, reverse) {
      var i, impulseL, impulseR, j, length, n, rate, ref;
      this.seconds = seconds;
      this.decay = decay;
      this.reverse = reverse;
      if (this.reverse == null) {
        this.reverse = false;
      }
      rate = Audanism.Audio.audioContext.sampleRate;
      length = rate * this.seconds;
      this.impulse = Audanism.Audio.audioContext.createBuffer(2, length, rate);
      impulseL = this.impulse.getChannelData(0);
      impulseR = this.impulse.getChannelData(1);
      n;
      for (i = j = 0, ref = length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        n = this.reverse ? length - i : i;
        impulseL[i] = (1 - Math.random() * 2) * Math.pow(1 - n / length, this.decay);
        impulseR[i] = (1 - Math.random() * 2) * Math.pow(1 - n / length, this.decay);
      }
    }

    Impulse.prototype.getBuffer = function() {
      return this.impulse;
    };

    return Impulse;

  })();

  window.Audanism.Audio.Module.Impulse = Impulse;

}).call(this);
