// Generated by CoffeeScript 1.4.0

/*
	Listens for Instagram pictures.
*/


(function() {
  var InstagramSourceAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  InstagramSourceAdapter = (function(_super) {

    __extends(InstagramSourceAdapter, _super);

    function InstagramSourceAdapter(listener) {
      this.listener = listener;
      InstagramSourceAdapter.__super__.constructor.call(this, this.listener);
      this.clientId = "f42a4ce0632e412ea5a0353c2b5e581f";
      this.photoSinceId = 0;
      this.tag = "belieber";
      this.queryUrl = "http://api.instagram.com/v1/tags/belieber/media/recent?client_id=" + this.clientId;
    }

    InstagramSourceAdapter.prototype.activate = function() {
      var _queryPhotos,
        _this = this;
      console.log('ISA activate');
      _this = this;
      _queryPhotos = this.queryPhotos;
      return setInterval(function() {
        return _this.queryPhotos.call(_this);
      }, 10000);
    };

    InstagramSourceAdapter.prototype.queryPhotos = function() {
      var _this = this;
      console.log('query instagram photots', this.queryUrl);
      return $.get(this.queryUrl, function(data) {
        return console.log('instagram data', data);
      });
    };

    InstagramSourceAdapter.prototype.adaptSourceData = function() {};

    return InstagramSourceAdapter;

  })(SourceAdapter);

  window.InstagramSourceAdapter = InstagramSourceAdapter;

}).call(this);
