// Generated by CoffeeScript 1.10.0

/*
	Interpreter
 */

(function() {
  var Interpreter;

  Interpreter = (function() {
    function Interpreter(sourceAdapters) {
      this.sourceAdapters = sourceAdapters;
    }

    Interpreter.prototype.addSourceAdapter = function(sourceAdapter) {};

    Interpreter.prototype.startListenToSources = function() {};

    return Interpreter;

  })();

  window.Audanism.Environment.Interpreter = Interpreter;

}).call(this);
