// Generated by CoffeeScript 1.4.0

/*
	Monoism synth - just a sine
*/


(function() {
  var Monoism;

  Monoism = (function() {

    function Monoism(note) {
      this.note = note;
      this.effectChain = Audanism.Audio.audioContext.createGain();
      this.volNode = Audanism.Audio.audioContext.createGain();
      this.volNode.gain.value = 0.25;
      this.effectChain.connect(this.volNode);
      this.volNode.connect(Audanism.Audio.audioContext.destination);
      this.freq = Audanism.Audio.Harmonizer.getFreqFromNote(this.note);
      this.osc = Audanism.Audio.audioContext.createOscillator();
      this.osc.frequency.setValueAtTime(this.freq, 0);
      this.osc.connect(this.effectChain);
      this.osc.start(0);
    }

    Monoism.prototype.noteOn = function() {
      return this.osc.start(0);
    };

    Monoism.prototype.noteOff = function() {
      return this.osc.stop(Audanism.Audio.audioContext.currentTime + 0.1);
    };

    return Monoism;

  })();

  window.Audanism.Audio.Synthesizer.Monoism = Monoism;

}).call(this);
