// Generated by CoffeeScript 1.4.0

/*
	Listens for mouse actions and adapts them into data interpretable
	by the environment.
*/


(function() {
  var MouseSourceAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MouseSourceAdapter = (function(_super) {

    __extends(MouseSourceAdapter, _super);

    function MouseSourceAdapter() {}

    MouseSourceAdapter.prototype.activate = function() {};

    MouseSourceAdapter.prototype.adaptSourceData = function() {};

    return MouseSourceAdapter;

  })(Audanism.SourceAdapter.SourceAdapter);

  window.Audanism.SourceAdapter.MouseSourceAdapter = MouseSourceAdapter;

}).call(this);
