// Generated by CoffeeScript 1.4.0

/*
	Listens for mouse actions and adapts them into data interpretable
	by the environment.
*/


(function() {
  var MouseSourceAdapter;

  MouseSourceAdapter = (function() {

    function MouseSourceAdapter() {}

    MouseSourceAdapter.prototype.activate = function() {};

    MouseSourceAdapter.prototype.adaptSourceData = function() {};

    return MouseSourceAdapter;

  })();

  window.MouseSourceAdapter = MouseSourceAdapter;

}).call(this);
