// Generated by CoffeeScript 1.4.0
(function() {
  var NeuroticismFactor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NeuroticismFactor = (function(_super) {

    __extends(NeuroticismFactor, _super);

    function NeuroticismFactor() {
      NeuroticismFactor.__super__.constructor.call(this, Factor.TYPE_NEUROTICISM, 10);
    }

    return NeuroticismFactor;

  })(Factor);

  window.NeuroticismFactor = NeuroticismFactor;

}).call(this);
