// Generated by CoffeeScript 1.10.0
(function() {
  var NeuroticismFactor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  NeuroticismFactor = (function(superClass) {
    extend(NeuroticismFactor, superClass);

    function NeuroticismFactor() {
      NeuroticismFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_NEUROTICISM);
    }

    return NeuroticismFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.NeuroticismFactor = NeuroticismFactor;

}).call(this);
