// Generated by CoffeeScript 1.4.0

/*
	A node cell
*/


(function() {
  var NodeCell;

  NodeCell = (function() {

    NodeCell.prototype.clone = function() {
      return new NodeCell(this.factorType, this.factorValue);
    };

    function NodeCell(factorType, factorValue) {
      this.factorType = factorType;
      this.factorValue = factorValue;
    }

    return NodeCell;

  })();

  window.NodeCell = NodeCell;

}).call(this);
