// Generated by CoffeeScript 1.4.0

/*
FactorBucket
*/


(function() {
  var FactorBucket;

  FactorBucket = (function() {

    function FactorBucket(factorType, factorValue) {
      console.log("FactorBucket", factorType, factorValue);
      this.factorType = factorType;
      this.factorValue = factorValue;
    }

    return FactorBucket;

  })();

  window.FactorBucket = FactorBucket;

}).call(this);
