// Generated by CoffeeScript 1.4.0
(function() {
  var OpennessFactor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OpennessFactor = (function(_super) {

    __extends(OpennessFactor, _super);

    function OpennessFactor() {
      OpennessFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_OPENNESS);
    }

    return OpennessFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.OpennessFactor = OpennessFactor;

}).call(this);
