// Generated by CoffeeScript 1.10.0
(function() {
  var OpennessFactor,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  OpennessFactor = (function(superClass) {
    extend(OpennessFactor, superClass);

    function OpennessFactor() {
      OpennessFactor.__super__.constructor.call(this, Audanism.Factor.Factor.TYPE_OPENNESS);
    }

    return OpennessFactor;

  })(Audanism.Factor.Factor);

  window.Audanism.Factor.OpennessFactor = OpennessFactor;

}).call(this);
