// Generated by CoffeeScript 1.4.0

/*
	Organism
*/


(function() {
  var Organism;

  Organism = (function() {

    Organism.NUM_FACTORS = 5;

    Organism.DEFAULT_NUM_NODES = 40;

    Organism.STRESS_THRESHOLD_ENTER = 1;

    Organism.STRESS_THRESHOLD_LEAVE = 2;

    function Organism(numNodes) {
      var i;
      if (numNodes == null) {
        numNodes = -1;
      }
      this._sumDisharmony = 0;
      this._actualDisharmony = 0;
      this._inStressMode = true;
      this._factors = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 1, _ref = Organism.NUM_FACTORS; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
          _results.push(Factor.createFactor(i, 0));
        }
        return _results;
      })();
      if (numNodes <= 0) {
        numNodes = Organism.DEFAULT_NUM_NODES;
      }
      this._nodes = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 1; 1 <= numNodes ? _i <= numNodes : _i >= numNodes; i = 1 <= numNodes ? ++_i : --_i) {
          _results.push(new Node());
        }
        return _results;
      })();
      console.log("Created nodes:", numNodes, this._nodes);
      this.disharmonyCalculator = new DisharmonyCalculator(this);
      this.disharmonyHistory = [];
      this._gui = new GUI;
    }

    Organism.prototype.getNodes = function() {
      return this._nodes;
    };

    Organism.prototype.getFactors = function() {
      return this._factors;
    };

    Organism.prototype.getFactorOfType = function(factorType) {
      var factor, foundFactor, _i, _len, _ref;
      foundFactor = null;
      _ref = this._factors;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        factor = _ref[_i];
        if (factor.factorType === factorType) {
          foundFactor = factor;
        }
      }
      return foundFactor;
    };

    Organism.prototype.performNodeComparison = function(numComparisons) {
      var comparisonMode, factor, i, nodes, _i, _j, _len, _ref;
      if (numComparisons == null) {
        numComparisons = 1;
      }
      console.log("#performNodeComparison, " + DisharmonyCalculator.NODE_COMPARISON_MODE_FACTOR_HARMONY);
      this.disharmonyCalculator.debug = true;
      for (i = _i = 1; 1 <= numComparisons ? _i <= numComparisons : _i >= numComparisons; i = 1 <= numComparisons ? ++_i : --_i) {
        nodes = this._getRandomNodes(2);
        comparisonMode = this._inStressMode ? DisharmonyCalculator.NODE_COMPARISON_MODE_FACTOR_HARMONY : DisharmonyCalculator.NODE_COMPARISON_MODE_ORGANISM_HARMONY;
        this.disharmonyCalculator.alterNodesInComparisonMode(nodes, comparisonMode);
      }
      this.disharmonyCalculator.debug = false;
      this._sumDisharmony = this.disharmonyCalculator.getSummedOrganismDisharmony(this);
      this._actualDisharmony = this.disharmonyCalculator.getActualOrganismDisharmony(this);
      this.disharmonyHistory.push([this.disharmonyHistory.length, this._sumDisharmony]);
      _ref = this._factors;
      for (_j = 0, _len = _ref.length; _j < _len; _j++) {
        factor = _ref[_j];
        factor.disharmony = this.disharmonyCalculator.getFactorDisharmonyForNodes(factor, this._nodes);
      }
      if (!this._inStressMode && this._actualDisharmony < Organism.STRESS_THRESHOLD_ENTER) {
        return this._inStressMode = true;
      } else if (this._inStressMode && this._actualDisharmony > Organism.STRESS_THRESHOLD_LEAVE) {
        return this._inStressMode = false;
      }
    };

    Organism.prototype.getDisharmonyHistoryData = function(numEntries) {
      if (numEntries == null) {
        numEntries = 300;
      }
      if (numEntries > 0) {
        return this.disharmonyHistory.slice(-numEntries);
      } else {
        return this.disharmonyHistory.slice(-this.disharmonyHistory.length);
      }
    };

    Organism.prototype._getRandomNodes = function(numNodes) {
      var allNodeIndexes, i, nodeIndexes, _i, _j, _len, _ref, _results, _results1;
      allNodeIndexes = (function() {
        _results = [];
        for (var _i = 0, _ref = this._nodes.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this);
      nodeIndexes = (function() {
        var _j, _results1;
        _results1 = [];
        for (i = _j = 1; 1 <= numNodes ? _j <= numNodes : _j >= numNodes; i = 1 <= numNodes ? ++_j : --_j) {
          _results1.push(allNodeIndexes.splice(Math.floor(Math.random() * allNodeIndexes.length), 1));
        }
        return _results1;
      })();
      _results1 = [];
      for (_j = 0, _len = nodeIndexes.length; _j < _len; _j++) {
        i = nodeIndexes[_j];
        _results1.push(this._nodes[i]);
      }
      return _results1;
    };

    return Organism;

  })();

  window.Organism = Organism;

}).call(this);
