// Generated by CoffeeScript 1.10.0
(function() {
  var OrganismDisarmonyCalculator;

  OrganismDisarmonyCalculator = (function() {
    function OrganismDisarmonyCalculator() {}

    OrganismDisarmonyCalculator.getSummedOrganismDisharmony = function(organism) {};

    OrganismDisarmonyCalculator.getActualOrganismDisharmony = function(organism) {};

    return OrganismDisarmonyCalculator;

  })();

  window.Audanism.Calculator.OrganismDisarmonyCalculator = OrganismDisarmonyCalculator;

}).call(this);
