// Generated by CoffeeScript 1.4.0

/*
	Alters the factor and/or node values randomly
*/


(function() {
  var RandomSourceAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RandomSourceAdapter = (function(_super) {

    __extends(RandomSourceAdapter, _super);

    RandomSourceAdapter.TIME_INTERVAL_ALTER_FACTORS = 2000;

    RandomSourceAdapter.PROBABILITY_ALTER_FACTORS = 1;

    RandomSourceAdapter.TIME_INTERVAL_ALTER_NODES = 500;

    RandomSourceAdapter.PROBABILITY_ALTER_NODES = 1;

    function RandomSourceAdapter(listener) {
      this.listener = listener;
      RandomSourceAdapter.__super__.constructor.call(this, this.listener);
    }

    RandomSourceAdapter.prototype.activate = function() {
      var _this = this;
      setInterval(function() {
        return _this.tryAlterFactors();
      }, RandomSourceAdapter.TIME_INTERVAL_ALTER_FACTORS);
      return setInterval(function() {
        return _this.tryAlterNodes();
      }, RandomSourceAdapter.TIME_INTERVAL_ALTER_NODES);
    };

    RandomSourceAdapter.prototype.getAdaptedSourceData = function(sourceData) {
      return sourceData;
    };

    RandomSourceAdapter.prototype.tryAlterFactors = function() {
      if (Math.floor((Math.random() + 1) / RandomSourceAdapter.PROBABILITY_ALTER_FACTORS) === 1) {
        return this.triggerInfluence({
          'random': {
            'object': 'factor',
            'num': 1,
            'valueModifier': 'rand'
          }
        });
      }
    };

    RandomSourceAdapter.prototype.tryAlterNodes = function() {
      if (Math.randomRange(Math.round(1 / RandomSourceAdapter.PROBABILITY_ALTER_NODES)) === 1) {
        return this.triggerInfluence({
          'random': {
            'object': 'node',
            'num': 'rand',
            'valueModifier': 'rand'
          }
        });
      }
    };

    return RandomSourceAdapter;

  })(SourceAdapter);

  window.RandomSourceAdapter = RandomSourceAdapter;

}).call(this);
