// Generated by CoffeeScript 1.4.0

/*
	Reverb
*/


(function() {
  var Reverb,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Reverb = (function(_super) {

    __extends(Reverb, _super);

    function Reverb(seconds, decay, wetAmount) {
      var _ref, _ref1, _ref2;
      this.seconds = seconds;
      this.decay = decay;
      this.wetAmount = wetAmount;
      if ((_ref = this.seconds) == null) {
        this.seconds = 1;
      }
      if ((_ref1 = this.decay) == null) {
        this.decay = 0.5;
      }
      if ((_ref2 = this.wetAmount) == null) {
        this.wetAmount = 1;
      }
      this.impulse = new Audanism.Audio.Module.Impulse(this.seconds, this.decay);
      this.rev = Audanism.Audio.audioContext.createConvolver();
      this.rev.buffer = this.impulse.getBuffer();
      this.wet = Audanism.Audio.audioContext.createGain();
      this.wet.gain.value = wetAmount;
      this.rev.connect(this.wet);
      Reverb.__super__.constructor.call(this, this.rev, this.wet);
    }

    return Reverb;

  })(Audanism.Audio.FX.FX);

  window.Audanism.Audio.FX.Reverb = Reverb;

}).call(this);
