// Generated by CoffeeScript 1.4.0

/*
	Synth base class
*/


(function() {
  var Synth;

  Synth = (function() {

    function Synth(audiolet, freq) {
      this.audiolet = audiolet;
      console.log('new Synth', freq);
      this.gen = new Sine(this.audiolet, freq);
      this.mod = new Saw(this.audiolet, freq * 2);
      this.modMulAdd = new MulAdd(this.audiolet, freq / 2, freq);
      this.gain = new Gain(this.audiolet);
      this.env = new PercussiveEnvelope(this.audiolet, 0, 0.02, 0.1);
      this.mod.connect(this.modMulAdd);
      this.modMulAdd.connect(this.gen);
      this.env.connect(this.gain, 0, 1);
      this.gen.connect(this.gain);
      this.gain.connect(this.audiolet.output);
    }

    return Synth;

  })();

  Audanism.Sound.Synth = Synth;

}).call(this);
