// Generated by CoffeeScript 1.4.0

/*
	Test instrument
*/


(function() {
  var TestInstrument,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestInstrument = (function(_super) {

    __extends(TestInstrument, _super);

    function TestInstrument(instrumentsIn) {
      this.instrumentsIn = instrumentsIn;
      TestInstrument.__super__.constructor.call(this, this.instrumentsIn, 'MonoistEnv', true);
    }

    TestInstrument.prototype.setupVoice = function(voice) {
      voice.masterVol.gain.value = 0.1;
      return voice.pan.setPosition(1 - Math.random() * 2, 0, 1 - Math.random() * 2);
    };

    return TestInstrument;

  })(Audanism.Audio.Instrument.Instrument);

  window.Audanism.Audio.Instrument.TestInstrument = TestInstrument;

}).call(this);
