// Generated by CoffeeScript 1.10.0

/*
	Listens for tweets.
 */

(function() {
  var TwitterSourceAdapter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TwitterSourceAdapter = (function(superClass) {
    extend(TwitterSourceAdapter, superClass);

    function TwitterSourceAdapter(listener) {
      this.listener = listener;
      TwitterSourceAdapter.__super__.constructor.call(this, this.listener);
      this.tweetSinceId = 0;
      this.queries = ["#belieber"];
      this.queryUrl = "http://search.twitter.com/search.json?q=" + (decodeURIComponent(this.queries.join(','))) + "&since_id=" + this.tweetSinceId + "&result_type=recent";
    }

    TwitterSourceAdapter.prototype.activate = function() {
      console.log('TSA activate');
      return this.queryTweets();
    };

    TwitterSourceAdapter.prototype.queryTweets = function() {
      return console.log('query tweets', this.queryUrl);
    };

    TwitterSourceAdapter.prototype.adaptSourceData = function() {};

    return TwitterSourceAdapter;

  })(Audanism.SourceAdapter.SourceAdapter);

  window.Audanism.SourceAdapter.TwitterSourceAdapter = TwitterSourceAdapter;

}).call(this);
